#url
register-center1.server.ip=localhost
register-center2.server.ip=localhost
register-center.urls=http://${register-center1.server.ip}:${register-center1.server.port}/eureka/,http://${register-center2.server.ip}:${register-center2.server.port}/eureka/
#port
register-center1.server.port=18001
register-center2.server.port=18002
zuul.server.port=19005
#config
enable-self-preservation=false
eviction-interval-timer-in-ms=5000
lease-expiration-duration-in-seconds=30
lease-renewal-interval-in-seconds=6
#ribbon
hystrix-command-default-execution-isolation-thread-timeoutInMilliseconds=60000
ribbon.ConnectTimeout=10000
ribbon.ReadTimeout=20000
ribbonName=ribbon-client
#server
serverName=config
serverPort=19003
url=http://${ribbonName}/simple/
